### ISSUE TITLE
Too much automated requests

### ISSUE THREAD

**Issue by LoopControl** [db0/KoboldAI-Horde#23]
After activating the Bridge, I was getting a new incoming request every couple seconds, I turned on logging and noticed that the vast majority (easily 90%+) of requests are from a single automated program generating text for a game (perhaps your own ?).

In the span of just a few minutes I saw the same kind of requests from this game text generation with prompts like "Giant insectoid queen in cavern description", "Hipster pelican description", and such coming in over and over again regardless of the model I was making available. I'm happy to donate with a bridge but if my 90% of my CPU and GPU time is going only to 1 person/automated-script, then it doesn't give me incentive to continue running the bridge.

Please turn those requests down if you have control over it or give us a way to ignore these kinds of requests.

**Comment by henk717** [comment]
This is still powering local software real people are using. Its related to an AI powered RPG. We have no control over individual requests especially since these will be requested from the IP of the user of the software.

So this is not a single individuals script, its multiple users who can not run the model locally.
